"""Export deterministic JSON schemas from the Pydantic domain source of truth."""

import argparse
import json
import re
from pathlib import Path

from ground_rule.models import CONTRACT_MODELS


def contract_schemas() -> dict[str, str]:
    result: dict[str, str] = {}
    for model in CONTRACT_MODELS:
        name = re.sub(r"(?<!^)(?=[A-Z])", "-", model.__name__).lower()
        schema = {
            "$schema": "https://json-schema.org/draft/2020-12/schema",
            **model.model_json_schema(),
        }
        result[name + ".schema.json"] = json.dumps(schema, indent=2, sort_keys=True) + "\n"
    return result


def typescript_contracts() -> str:
    """Mirror the existing schema shapes; runtime numeric/relational rules stay in Python/Ajv."""
    schemas = {model.__name__: model.model_json_schema() for model in CONTRACT_MODELS}
    definitions = {}
    for schema in schemas.values():
        definitions.update(schema.get("$defs", {}))
    definitions.update(schemas)

    def shape(schema: dict) -> str:
        if not schema:
            return "unknown"
        if "$ref" in schema:
            return schema["$ref"].split("/")[-1]
        if "const" in schema:
            return json.dumps(schema["const"])
        if "enum" in schema:
            return " | ".join(json.dumps(item) for item in schema["enum"])
        if "anyOf" in schema:
            return " | ".join(shape(item) for item in schema["anyOf"])
        kind = schema.get("type")
        if kind == "object":
            if "properties" not in schema:
                return "{ [key: string]: " + shape(schema["additionalProperties"]) + " }"
            required = schema.get("required", [])
            return (
                "{ "
                + "; ".join(
                    f"{name}{'' if name in required else '?'}: {shape(value)}"
                    for name, value in schema["properties"].items()
                )
                + " }"
            )
        if kind == "array":
            return f"Array<{shape(schema['items'])}>"
        if kind in {"string", "integer", "number", "boolean", "null"}:
            return {"integer": "number"}.get(kind, kind)
        raise ValueError(f"Unsupported schema shape: {schema}")

    return (
        "// Generated by scripts/export_contracts.py. Do not edit.\n"
        + "\n".join(
            f"export type {name} = {shape(schema)};" for name, schema in sorted(definitions.items())
        )
        + "\n"
    )


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--check", action="store_true", help="Fail if committed schemas have drifted"
    )
    args = parser.parse_args()
    contracts = Path(__file__).resolve().parents[1] / "contracts"
    for name, content in contract_schemas().items():
        path = contracts / name
        if args.check:
            if not path.exists() or path.read_text(encoding="utf-8") != content:
                raise SystemExit(f"Schema drift: {path}")
        else:
            path.write_text(content, encoding="utf-8")
    typescript = contracts / "domain.ts"
    content = typescript_contracts()
    if args.check:
        if not typescript.exists() or typescript.read_text(encoding="utf-8") != content:
            raise SystemExit(f"TypeScript contract drift: {typescript}")
    else:
        typescript.write_text(content, encoding="utf-8")
    print(f"{'Checked' if args.check else 'Exported'} {len(CONTRACT_MODELS)} schemas")


if __name__ == "__main__":
    main()
