import { chromium } from '../apps/web/node_modules/playwright/index.mjs';
import fs from 'node:fs/promises';
import assert from 'node:assert/strict';

const directory = 'artifacts/release/outproof-confirmed-route-start';
await fs.mkdir(directory, { recursive: true });
const browser = await chromium.launch({ headless: true });
const context = await browser.newContext({ viewport: { width: 1440, height: 900 } });
await context.tracing.start({ screenshots: true, snapshots: true, sources: true });
const page = await context.newPage();
const report = { executed_at: new Date().toISOString(), scope: 'Fresh unmocked public Bengaluru search, original-origin refusal, explicit keyboard selection, full recompilation, proof/GO and subsequent zero-walking refusal. Agent-reviewed software evidence, no physical outing.', requests: [], errors: [], console_messages: [], request_failures: [], viewports: [] };
page.on('pageerror', error => report.errors.push(error.message));
page.on('console', message => { if (['warning', 'error'].includes(message.type()) && report.console_messages.length < 50) report.console_messages.push({ type: message.type(), text: message.text().slice(0, 1000) }); });
page.on('requestfailed', request => { const url = new URL(request.url()); report.request_failures.push({ resource: url.origin + url.pathname, error: request.failure()?.errorText }); });
const responseReceipt = async response => {
  const body = await response.json();
  report.requests.push({ status: response.status(), request_id: response.headers()['x-request-id'], controls: response.request().postDataJSON().controls, body });
  return body;
};
try {
  await page.goto('https://outproof-web.onrender.com', { waitUntil: 'networkidle', timeout: 65000 });
  report.version = await (await context.request.get('https://outproof-api.onrender.com/v1/version')).json();
  assert.equal(report.version.commit, process.env.EXPECTED_COMMIT);
  const manifest = await context.request.get('https://outproof-web.onrender.com/manifest.webmanifest');
  assert.equal(manifest.status(), 200);
  assert.equal((await manifest.json()).name, 'Outproof');
  report.manifest_brand = 'Outproof';
  await page.getByLabel('Search for your starting area').fill('Bengaluru');
  const searchWait = page.waitForResponse(response => response.url().endsWith('/v1/locations/search'));
  await page.getByRole('button', { name: 'Search places', exact: true }).click();
  const search = await searchWait;
  assert.equal(search.status(), 200);
  const choices = (await search.json()).results.filter(point => point.label.includes('India'));
  assert.ok(choices.length);
  report.selected_start = choices[0];
  await page.getByRole('button', { name: choices[0].label, exact: true }).press('Enter');
  const mapToggle = page.getByRole('button', { name: 'Hide map', exact: true });
  assert.equal(await mapToggle.evaluate(element => element === document.activeElement), true);
  const button = page.getByRole('button', { name: 'Compile one live plan', exact: true });
  await page.waitForFunction(element => !element.disabled, await button.elementHandle(), { timeout: 65000 });
  await page.getByText('Add a rule or preference', { exact: true }).click();
  await page.getByLabel(/Anything else/).fill("I prefer somewhere quiet. I'm not vegan.");
  let responseWait = page.waitForResponse(response => response.url().endsWith('/v1/plans/compile'), { timeout: 190000 });
  await page.keyboard.press('Tab'); await button.focus(); await page.keyboard.press('Enter');
  const refusal = await responseReceipt(await responseWait);
  assert.equal(report.requests[0].status, 409);
  assert.equal(refusal.code, 'UNSUPPORTED_CONSTRAINT');
  assert.ok(refusal.suggested_origin);
  assert.deepEqual(report.requests[0].controls.origin, choices[0].coordinates);
  const confirm = page.getByRole('button', { name: 'Set start to mapped route', exact: true });
  await confirm.waitFor();
  await page.waitForFunction(() => document.activeElement?.getAttribute('role') === 'alert');
  await page.getByText(/Travel from your current pin/).waitFor();
  assert.equal(await page.getByRole('button', { name: 'GO', exact: true }).count(), 0);
  await page.screenshot({ path: `${directory}/refusal-desktop.png`, fullPage: true });
  for (const width of [320, 360, 390, 768, 1024, 1440]) {
    await page.setViewportSize({ width, height: 900 });
    assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true);
    report.viewports.push({ width, no_overflow: true });
  }
  await page.setViewportSize({ width: 390, height: 844 });
  await page.screenshot({ path: `${directory}/refusal-mobile.png`, fullPage: true });
  await page.setViewportSize({ width: 1440, height: 900 });
  await confirm.focus();
  assert.equal(await confirm.evaluate(element => getComputedStyle(element).outlineStyle !== 'none'), true);
  await page.keyboard.press('Enter');
  assert.equal(await confirm.count(), 0);
  assert.equal(await button.evaluate(element => element === document.activeElement), true);
  assert.equal(report.requests.length, 1, 'Selecting a point must not compile automatically');
  await page.getByRole('status').filter({ hasText: 'Starting point:' }).filter({ hasText: 'Mapped walking-route start' }).waitFor();
  await page.screenshot({ path: `${directory}/selected-mapped-start.png`, fullPage: true });
  await page.waitForTimeout(12000);
  responseWait = page.waitForResponse(response => response.url().endsWith('/v1/plans/compile'), { timeout: 190000 });
  const started = Date.now();
  await page.keyboard.press('Enter');
  const compiled = await responseReceipt(await responseWait);
  report.recompilation_ms = Date.now() - started;
  assert.equal(report.requests[1].status, 200);
  assert.equal(compiled.mode, 'LIVE');
  assert.equal(compiled.plan.stops.length, 1);
  assert.equal(compiled.plan.stops[0].place.name, 'Cubbon Park');
  assert.ok(compiled.proof.validation.checks.every(check => check.status === 'PASS'));
  assert.ok(compiled.proof.sources.every(source => source.source !== 'FIXTURE'));
  assert.deepEqual(report.requests[1].controls.origin, refusal.suggested_origin);
  const limits = ({ origin, departure_at, ...rest }) => rest;
  assert.deepEqual(limits(report.requests[1].controls), limits(report.requests[0].controls));
  await page.getByRole('heading', { name: 'One verified plan.', exact: true }).waitFor();
  await page.screenshot({ path: `${directory}/plan.png`, fullPage: true });
  await page.getByText(/Plan Proof ·/).click();
  await page.getByRole('heading', { name: 'Source observations · LIVE' }).waitFor();
  await page.screenshot({ path: `${directory}/proof.png`, fullPage: true });
  await page.getByRole('button', { name: 'GO', exact: true }).click();
  await page.getByText('Phone down.', { exact: true }).waitFor();
  await page.screenshot({ path: `${directory}/go.png`, fullPage: true });
  await page.getByRole('button', { name: 'Next step' }).click();
  await page.getByRole('button', { name: 'Back to plan', exact: true }).click();
  await page.setViewportSize({ width: 390, height: 844 });
  await page.screenshot({ path: `${directory}/plan-mobile.png`, fullPage: true });
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true);
  await page.getByRole('button', { name: 'Edit constraints', exact: true }).click();
  await page.getByLabel('Walking, all legs (min)', { exact: true }).fill('0');
  await page.waitForTimeout(12000);
  responseWait = page.waitForResponse(response => response.url().endsWith('/v1/plans/compile'), { timeout: 190000 });
  await button.focus(); await page.keyboard.press('Enter');
  const negative = await responseReceipt(await responseWait);
  assert.equal(report.requests[2].status, 409);
  assert.equal(negative.status, 'FAILURE');
  assert.equal(report.requests[2].controls.max_walking_minutes, 0);
  assert.deepEqual(report.requests[2].controls.origin, refusal.suggested_origin);
  await page.getByRole('alert').waitFor();
  await page.waitForFunction(() => document.activeElement?.getAttribute('role') === 'alert');
  assert.equal(await page.getByLabel('Walking, all legs (min)', { exact: true }).inputValue(), '0');
  assert.equal(await page.getByRole('heading', { name: 'One verified plan.', exact: true }).count(), 0);
  assert.equal(await page.getByRole('button', { name: 'GO', exact: true }).count(), 0);
  await page.screenshot({ path: `${directory}/walking-zero-refusal-mobile.png`, fullPage: true });
  assert.deepEqual(report.errors, []);
  report.version_after = await (await context.request.get('https://outproof-api.onrender.com/v1/version')).json();
  assert.equal(report.version_after.commit, report.version.commit);
  report.status = 'PASS';
} catch (error) {
  report.status = 'FAIL'; report.failure = String(error);
  await page.screenshot({ path: `${directory}/failure.png`, fullPage: true }).catch(() => {});
}
await context.tracing.stop({ path: `${directory}/trace.zip` });
await context.close(); await browser.close();
await fs.writeFile(`${directory}/receipt.json`, JSON.stringify(report, null, 2) + '\n');
console.log(JSON.stringify({ status: report.status, requests: report.requests.map(request => ({ status: request.status, request_id: request.request_id })), failure: report.failure }));
if (report.status !== 'PASS') process.exitCode = 1;
