import { chromium } from '../apps/web/node_modules/playwright/index.mjs';
import fs from 'node:fs/promises';
import assert from 'node:assert/strict';
const label=process.env.PUBLIC_RUN_LABEL??`outproof-tab-keyboard-${Date.now()}`;assert.match(label,/^[a-z0-9-]+$/);const directory=`artifacts/release/${label}`;await fs.mkdir(directory);
const browser=await chromium.launch({headless:true});const context=await browser.newContext({viewport:{width:390,height:844}});await context.tracing.start({screenshots:true,snapshots:true,sources:true});const page=await context.newPage();
const report={executed_at:new Date().toISOString(),scope:'Unmocked public software journey using only Tab/Enter/text typing for interaction; no programmatic focus, pointer clicks, human hardware or physical visit',status:'PENDING',errors:[],tab_steps:[]};page.on('pageerror',e=>report.errors.push(e.message));
async function tabTo(locator,label){for(let i=0;i<120;i++){if(await locator.evaluate(e=>e===document.activeElement)){report.tab_steps.push({target:label,tabs:i});return;}await page.keyboard.press('Tab');}throw new Error('Keyboard focus could not reach '+label);}
try{
 await page.goto('https://outproof-web.onrender.com',{waitUntil:'networkidle'});report.version=await(await context.request.get('https://outproof-api.onrender.com/v1/version')).json();assert.equal(report.version.commit,process.env.EXPECTED_COMMIT);
 const preset=page.getByRole('button',{name:'Try the Chandigarh walking start',exact:true});await tabTo(preset,'reviewed public start');await page.keyboard.press('Enter');
 const details=page.locator('summary').filter({hasText:'Add a rule or preference'});await tabTo(details,'optional preference summary');await page.keyboard.press('Enter');const text=page.getByLabel(/Anything else/);await tabTo(text,'Gemma preference input');await page.keyboard.type("I prefer somewhere quiet. I'm not vegan.");
 const compile=page.getByRole('button',{name:'Compile one live plan',exact:true});await tabTo(compile,'compile');await page.waitForFunction(()=>!document.querySelector('button[type="submit"]').disabled,null,{timeout:65000});const wait=page.waitForResponse(r=>r.url().endsWith('/v1/plans/compile'),{timeout:190000});await page.keyboard.press('Enter');const response=await wait;const wireBody=await response.text();const body=JSON.parse(wireBody);report.request={wire_body:wireBody,status:response.status(),request_id:response.headers()['x-request-id'],controls:response.request().postDataJSON().controls,body};assert.equal(response.status(),200);assert.equal(body.mode,'LIVE');assert.equal(body.plan.stops.length,1);assert.equal(body.plan.stops[0].place.name,'Shanti Kunj');assert.ok(body.proof.validation.checks.every(c=>c.status==='PASS'));assert.ok(body.proof.sources.every(s=>s.source!=='FIXTURE'));
 const proof=page.locator('summary').filter({hasText:'Plan Proof'});await tabTo(proof,'proof');await page.keyboard.press('Enter');await page.getByRole('heading',{name:'Source observations · LIVE'}).waitFor();await page.screenshot({path:directory+'/proof-mobile.png',fullPage:true});
 const go=page.getByRole('button',{name:'GO',exact:true});await tabTo(go,'GO');assert.equal(await go.evaluate(e=>getComputedStyle(e).outlineStyle!=='none'),true);await page.keyboard.press('Enter');await page.getByText('Phone down.',{exact:true}).waitFor();await page.screenshot({path:directory+'/go-mobile.png',fullPage:true});
 await tabTo(page.getByRole('button',{name:'Next step',exact:true}),'Next');await page.keyboard.press('Enter');await tabTo(page.getByRole('button',{name:'Back to plan',exact:true}),'Back');await page.keyboard.press('Enter');await page.getByRole('heading',{name:'One verified plan.',exact:true}).waitFor();assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);assert.deepEqual(report.errors,[]);report.version_after=await(await context.request.get('https://outproof-api.onrender.com/v1/version')).json();assert.equal(report.version_after.commit,report.version.commit);report.status='PASS';
}catch(e){report.status='FAIL';report.failure=String(e);await page.screenshot({path:directory+'/failure.png',fullPage:true}).catch(()=>{});}
await context.tracing.stop({path:directory+'/trace.zip'});await context.close();await browser.close();await fs.writeFile(directory+'/receipt.json',JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify({status:report.status,tab_steps:report.tab_steps,failure:report.failure,request_id:report.request?.request_id}));if(report.status!=='PASS')process.exitCode=1;
